set ( "${PROJECT}_VERSION_GENERATION" 0 )
set ( "${PROJECT}_VERSION_BRANCH" 0 )
set ( "${PROJECT}_VERSION_RELEASE" 0 )
set ( "${PROJECT}_VERSION_DEV" 1 )
set ( "${PROJECT}_VERSION" ${${PROJECT}_VERSION_GENERATION}.${${PROJECT}_VERSION_BRANCH}.${${PROJECT}_VERSION_RELEASE}.${${PROJECT}_VERSION_DEV} )
set ( "ver" ${${PROJECT}_VERSION_GENERATION}.${${PROJECT}_VERSION_BRANCH}.${${PROJECT}_VERSION_RELEASE}.${${PROJECT}_VERSION_DEV} )

set ( supported_languages CXX C )

set ( CMAKE_CXX_STANDARD 23 )

set ( "${PROJECT}_BINARY_DIR" bin )
set ( "${PROJECT}_SOURCE_DIR" src )
#set ( "${PROJECT}_LIBS_DIR" libs )

set ( CMAKE_INCLUDE_PATH ${${PROJECT}_SOURCE_DIR} )
#set ( CMAKE_LIBRARY_PATH ${${PROJECT}_LIBS_DIR} )
set ( EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${${PROJECT}_BINARY_DIR} )
